function shuffleWords(paragraph) {
  // Split the paragraph into words
  const words = paragraph.split(/\s+/);

  // Shuffle the words array using Fisher-Yates algorithm
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [words[i], words[j]] = [words[j], words[i]]; // Swap elements
  }

  // Join the shuffled words back into a single string
  return words.join(" ");
}

// 42 casa 78 perro 56 árbol 23 libro 91 coche 67 sol 84 luna 35 ventana 29 silla 52 mesa 11 ventana 77 pájaro 18 calle 39 jardín 82 amigo 64 luz 47 coche 53 libro 99 árbol 74 ventana 31 sol 45 casa 88 perro 12 luna 76 mesa 24 jardín 83 silla 57 pájaro 92 calle 16 amigo 68 luz 21 ventana 54 sol 87 libro 13 coche 79 árbol 36 mesa 46 perro 55 luna 19 silla 71 jardín 94 amigo 26 luz 63 ventana 32 casa 85 sol 41 libro 58 coche 22 árbol 79 ventana 28 pájaro 50 luna 95 jardín 61 amigo 38 silla 76 luz 16 perro 43 casa 89 sol 25 libro 77 coche 67 árbol 54 ventana 99 luna 44 jardín 21 silla 82 amigo 91 luz 35 perro 72 casa 16 ventana 50 libro 84 coche 63 árbol 29 luna 57 silla 42 jardín 96 amigo 78 sol 27 ventana 18 perro 64 casa 82 libro 39 luna 90 coche 53 jardín 77 silla 41 luz 28 árbol 15 ventana 83 amigo 61 sol 96 perro 21 casa 50 libro 79 coche 36 luna 67 jardín 92 silla 47 luz 18 ventana 55 amigo 73 sol 29 perro 84 casa 61 libro 48 coche 99 jardín 12 luna 56 silla 71 ventana 23 amigo 90 sol 38 perro 67 casa 84 libro 29 luna 56 jardín 74 silla 41 luz 18 ventana 95 amigo 82 sol 30 perro 48 casa 57 libro 16 coche 71 árbol 89 jardín 54 silla 99 luna 44 ventana 12 amigo 63 sol 25 perro 38 casa 72 libro 91 coche 54 árbol 89 luna 26 jardín 45 silla 63 luz 12 ventana 56 amigo 77 sol 84 perro 21 casa 39 libro 68 coche 53 árbol 74 luna 15 jardín 99 silla 88 luz 32 ventana 57 amigo 19 sol 46 perro 64 casa 85 libro 28 coche 92 jardín 51 luna 76 silla 41 ventana 99 amigo 33 sol 24 perro 57 casa 88 libro 76 coche 45 árbol 29 luna 63 jardín 84 silla 50 luz 21 ventana 17 amigo 92 sol 38 perro 47 casa 79 libro 54 coche 33 árbol 91 luna 16 jardín 63 silla 84 luz 22 ventana 96 amigo 55 sol 39 perro 72 casa 48 libro 87 coche 29 luna 53 jardín 61 silla 84 luz 22 ventana 90 amigo 31 sol 57 perro 44 casa 82 libro 28 coche 99 jardín 15 luna 68 silla 41 luz 77 ventana 16 amigo

// La vida diaria de una persona puede ser muy variada dependiendo de dónde viva y qué haga. En general, la mayoría de las personas comienzan su día despertándose por la mañana. Después de levantarse, muchas personas se preparan para ir al trabajo, a la escuela o para realizar sus actividades diarias. Normalmente, las personas se duchan, se visten y toman el desayuno. El desayuno es una comida muy importante, ya que nos da energía para comenzar el día con fuerza. Algunas personas prefieren un desayuno ligero, como una fruta o un yogur, mientras que otras disfrutan de algo más grande, como huevos o pan tostado.Después del desayuno, la mayoría de las personas se dirigen a sus trabajos o estudios. Muchas personas van a trabajar en oficinas, fábricas o tiendas, mientras que los estudiantes asisten a clases. Durante el día, las personas suelen tener descansos para comer y relajarse un poco antes de continuar con sus tareas. Estos descansos son importantes porque permiten que el cuerpo y la mente se recuperen.A medida que avanza el día, las personas enfrentan diferentes desafíos. En el trabajo, puede haber reuniones, proyectos o tareas que deben completarse. En la escuela, los estudiantes aprenden sobre diferentes materias, como matemáticas, ciencias o historia. A veces, las personas encuentran momentos difíciles, pero también hay momentos de satisfacción cuando logran terminar algo importante.Al final de la jornada laboral o escolar, la mayoría de las personas regresan a casa. Este es un momento para relajarse y descansar después de un día ajetreado. Algunas personas disfrutan viendo la televisión, leyendo un libro o pasando tiempo con sus familias. La cena es otra comida importante del día. Es un momento en que muchas familias se sientan juntas para hablar sobre cómo fue su día. La cena suele ser una comida más ligera

//La vida contemporánea ha experimentado una serie de transformaciones debido a los avances tecnológicos y a los cambios en la forma en que interactuamos con el mundo. Uno de los principales cambios ha sido la manera en que trabajamos y nos comunicamos. Hace algunas décadas, la mayoría de las personas tenía empleos que requerían su presencia física en oficinas, fábricas o tiendas. Sin embargo, hoy en día, gracias a la tecnología y la expansión del internet, cada vez más personas tienen la oportunidad de trabajar de forma remota, desde la comodidad de sus hogares o desde cualquier lugar con acceso a internet.El teletrabajo, o trabajo a distancia, ha cambiado radicalmente la estructura de la jornada laboral. Muchas personas ya no necesitan gastar tiempo en desplazarse a sus lugares de trabajo, lo que les permite tener más flexibilidad en sus horarios. Esta flexibilidad puede ser beneficiosa para a
// Example usage:
//
//
// El mundo contemporáneo está marcado por una compleja interrelación de factores socioculturales, económicos y tecnológicos que influyen profundamente en la manera en que las sociedades evolucionan. Uno de los fenómenos más evidentes en este contexto es la globalización, un proceso multifacético que, si bien ha facilitado el intercambio de bienes, servicios y conocimientos a escala global, también ha generado dinámicas de interdependencia que pueden ser problemáticas. A nivel económico, la globalización ha promovido la consolidación de grandes conglomerados multinacionales, los cuales operan en múltiples jurisdicciones y que, en ocasiones, trascienden el poder regulador de los gobiernos nacionales. Esto plantea serios desafíos en términos de gobernanza, ya que los Estados, especialmente los menos desarrollados, ven disminuida su capacidad de intervenir en sus economías para proteger los intereses de sus ciudadanos.Aunado a ello, el impacto de la globalización en las culturas locales es
const paragraph =
  "El, mundo actual—con su ritmo acelerado, sus avances tecnológicos y, sus desafíos globales—es un lugar fascinante, pero también complejo. ¿Cómo afectan estos, cambios en nuestra vida diaria? En primer lugar, la tecnología, sin duda, ha transformado nuestras vidas; desde la forma en que trabajamos hasta, cómo nos comunicamos. Por ejemplo, las redes sociales, los teléfonos inteligentes y, las plataformas de comunicación instantánea han cambiado, drásticamente, nuestra forma de interactuar. ¡Imagínate! La posibilidad de enviar un mensaje en, segundos, a alguien al otro lado del mundo—sin tener que esperar semanas para una carta—es impresionante. Sin embargo, también hay, desventajas ventana calle a silla amigo profundamente perro 33 84 la 38 libro ventana 92 el que desafíos y 19 coche calle de 88 29 50 globalización en ser 55 silla desarrollados, 35 En luna 95 sus vida 44 marcado 15 facilitado luna jardín libro 91 proceso operan términos pájaro silla 29 32 mundo sol casa 21 54 dónde interrelación 12 casa 71 los 48 96 79 casa 57 mayoría 43 44 trascienden 19 una libro 89 67 15 económicos 77 luz menos 47 21 99 53 38 libro amigo ventana en 85 en 56 la 54 17 silla perro casa jardín 12 84 sol libro la perro ventana la amigo más 18 jardín plantea sol jardín 42 23 amigo 29 casa 12 54 sol 47 perro intervenir perro 16 silla 41 76 nivel amigo globalización silla 64 Uno 50 las amigo 32 sol 53";
const shuffledParagraph = shuffleWords(paragraph);
console.log(shuffledParagraph);
