# Generated by Django 5.1 on 2024-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing_Strings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages_text',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
