# Generated by Django 5.1 on 2024-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing_Strings', '0002_alter_languages_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages_text',
            name='text',
            field=models.TextField(),
        ),
    ]
